name: deep_clustering_env
channels:
  - conda-forge
  - nvidia
dependencies:
  - imageio
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - pyarrow
  - python=3.9
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - 